update readme
screwdriver-cd/build-bookend pull request #1
Opened 2016-11-16 19:46 UTC by petey

Describe the bookend module

2016-11-16 21:42 UTC, tkyi approved these changes
LGTM
![](https://media1.giphy.com/media/111M2gQJJ8Ms3S/200w.gif)

2016-11-16 22:03 UTC, d2lam commented on README.md
> +    { 'sd-sample': new SampleBookend() },
Can you add comment for the type of `defaultModules` in the function definition? 
https://github.com/screwdriver-cd/build-bookend/blob/master/index.js#L30-L36

2016-11-17 00:43 UTC, d2lam requested changes
LGTM 👍

2016-11-17 00:44 UTC, d2lam approved these changes

2016-11-17 00:44 UTC, merged