feat(#2852): implement new bookend configuration and key mapping
screwdriver-cd/build-bookend pull request #24
Opened 2023-04-03 23:54 UTC by pritamstyz4ever

## Context

Bookend configuration needs to be flexible and aware of the environment  and executor to pick the correct set of bookends

## Objective

This PR adds logic to select bookends by a key name which comprises of `cluster_name.env_name.executor_name`
and defaults to build cluster name or default configuration

## References

[](https://github.com/screwdriver-cd/screwdriver/issues/2852)

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-04-04 16:46 UTC, DekusDenial requested changes
maybe use hapi/hoek for all these traversal method? we define the bookend object and know the levels

2023-04-04 16:52 UTC, DekusDenial commented
cc @y-oksaku

2023-04-04 19:06 UTC, tkyi commented on index.js
> + * @param  {Array}           list List of cached plugins
```suggestion
 * @param  {Array}         defaultModules List of default plugins
 * @param  {Array}         cachedModules List of cached plugins
```

2023-04-04 19:07 UTC, tkyi commented on index.js
> + * @param  {string} bookendKey Bookend key name
```suggestion
 * @param {String} bookendKey Bookend key name
```

2023-04-05 15:13 UTC, pritamstyz4ever commented
> maybe use hapi/hoek for all these traversal method? we define the bookend object and know the levels

for selectBookends, we could probably use Hapi but the traverseBookends will be needed for initializing the modules.
I can also update the key from `.` based to an object like
```
 const { cluster, env, executor } = bookendKey
 ```

2023-04-06 18:21 UTC, DekusDenial requested changes
Other than that LGTM

2023-04-06 18:21 UTC, DekusDenial commented on index.js
> +        if (cachedModules[name]) {
Move cache into loadModule

2023-04-07 17:13 UTC, DekusDenial approved these changes

2023-04-07 18:09 UTC, merged